### ISSUE TITLE
Launch failure in Catalina

### ISSUE THREAD

**Issue by dhicks** [AstroBryGuy/EEKeeper-OSX#1]
Thanks for bundling EEKeeper into a Mac app.  Unfortunately, it's failing to launch for me.  I'm not seeing an error message or even a dock icon, suggesting the crash occurs very early in the launch process.  I'm not fluent in Mac crash reports, but as I read it the attached report suggests the problem might be with Wineskin.  

I'm running Catalina, and given this repository hasn't had any updates in two years I'm wondering if the problem might be some 32-bit code in Wineskin.  From what I can tell, there's not yet a 64-bit version of Wine, in which case EEKeeper can't be updated to run on Catalina.  Is that correct?  

[Crash report](https://github.com/AstroBryGuy/EEKeeper-OSX/files/3924195/EEKeeper-OSX_v1.0.4.0a_cr.txt)

**Comment by AstroBryGuy** [comment]
WIne does not support Catalina at this time. Sorry.
