### ISSUE TITLE
Seems not to be working in MacOS Catalina

### ISSUE THREAD

**Issue by winterflags** [AstroBryGuy/EEKeeper-OSX#2]
Tried opening the latest version of the wrapped app in MacOS Catalina 10.15.2, but it doesn't work unfortunately!

**Comment by AstroBryGuy** [comment]
Wine is not compatible with Catalina. This is 100% out of my hands.

See: https://wiki.winehq.org/MacOS:

> Official WineHQ packages of the development and stable branches are available for macOS 10.8 to 10.14 **(Wine won't work on macOS Catalina 10.15).**
